# Generated by Django 4.1.2 on 2022-10-09 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conhecimentoNegocios', models.CharField(default='', max_length=10, null=True)),
                ('modalidade', models.CharField(default='', max_length=15, null=True)),
                ('categoria', models.CharField(default='', max_length=100, null=True)),
                ('rendaNegocio', models.FloatField(null=True)),
                ('ajudaMicrocredito', models.CharField(default='', max_length=100, null=True)),
                ('valorMicrocredito', models.FloatField(null=True)),
                ('conhecimentoSegmento', models.CharField(default='', max_length=50, null=True)),
                ('temModeloNegocios', models.CharField(default='', max_length=10, null=True)),
                ('valorIniciarNegocio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('rendaFamiliar', models.FloatField()),
                ('jaEmpreeende', models.CharField(blank=True, max_length=5, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
        ),
    ]
