# Generated by Django 4.1.2 on 2022-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rendaFamiliar',
            field=models.FloatField(null=True),
        ),
    ]
